# Generated by Django 5.0.4 on 2024-04-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.URLField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
